name: Dev to Master
run-name: ${{ github.actor }} is testing automerge
on:
  push:
   branches:
     - develop
jobs:
  merge-on-master:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git config
        run: |
            git config --global user.email "email@email.com"
            git config --global user.name "renzzog777"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Merge dev to master
        run: |
            git fetch --unshallow
            git switch master
            git pull origin develop
            git merge  --strategy-option theirs --no-ff develop -m "Auto-merge dev to master"
            git push origin master
            
